# Generated by Django 4.0.3 on 2022-04-11 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('how_to_create', models.CharField(max_length=50)),
                ('madein', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.date)),
            ],
        ),
    ]
