# Generated by Django 4.0.3 on 2022-04-11 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_remove_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 10, 25, 30, 393725)),
        ),
    ]
